import '../core/transport.dart';
import 'archive.dart';
import 'ask.dart';
import 'attach.dart';
import 'authenticate.dart';
import 'clone.dart';
import 'confirm.dart';
import 'create.dart';
import 'delete.dart';
import 'disable.dart';
import 'discard.dart';
import 'echo.dart';
import 'enable.dart';
import 'get.dart';
import 'internals.dart';
import 'one.dart';
import 'preview.dart';
import 'publish.dart';
import 'regenerate.dart';
import 'register.dart';
import 'remove.dart';
import 'rename.dart';
import 'resend.dart';
import 'reveal.dart';
import 'rotate.dart';
import 'save.dart';
import 'send.dart';
import 'set.dart';
import 'test.dart';
import 'un.dart';
import 'update.dart';
import 'verify.dart';

class HubNamespace {
  final Transport _transport;
  HubNamespace(this._transport);
  HubArchiveModule get archive => HubArchiveModule(_transport);
  HubAskModule get ask => HubAskModule(_transport);
  HubAttachModule get attach => HubAttachModule(_transport);
  HubAuthenticateModule get authenticate => HubAuthenticateModule(_transport);
  HubCloneModule get clone => HubCloneModule(_transport);
  HubConfirmModule get confirm => HubConfirmModule(_transport);
  HubCreateModule get create => HubCreateModule(_transport);
  HubDeleteModule get delete => HubDeleteModule(_transport);
  HubDisableModule get disable => HubDisableModule(_transport);
  HubDiscardModule get discard => HubDiscardModule(_transport);
  HubEchoModule get echo => HubEchoModule(_transport);
  HubEnableModule get enable => HubEnableModule(_transport);
  HubGetModule get get_ => HubGetModule(_transport);
  HubInternalsModule get internals => HubInternalsModule(_transport);
  HubOneModule get one => HubOneModule(_transport);
  HubPreviewModule get preview => HubPreviewModule(_transport);
  HubPublishModule get publish => HubPublishModule(_transport);
  HubRegenerateModule get regenerate => HubRegenerateModule(_transport);
  HubRegisterModule get register => HubRegisterModule(_transport);
  HubRemoveModule get remove => HubRemoveModule(_transport);
  HubRenameModule get rename => HubRenameModule(_transport);
  HubResendModule get resend => HubResendModule(_transport);
  HubRevealModule get reveal => HubRevealModule(_transport);
  HubRotateModule get rotate => HubRotateModule(_transport);
  HubSaveModule get save => HubSaveModule(_transport);
  HubSendModule get send => HubSendModule(_transport);
  HubSetModule get set_ => HubSetModule(_transport);
  HubTestModule get test => HubTestModule(_transport);
  HubUnModule get un => HubUnModule(_transport);
  HubUpdateModule get update => HubUpdateModule(_transport);
  HubVerifyModule get verify => HubVerifyModule(_transport);
}
